# numpy tricks

### 1. np.sort:Return a sorted copy of an array.

In [1]:
import numpy as np
import warnings 
warnings. filterwarnings('ignore')

In [2]:
a = np.random.randint(1,100,15)

In [3]:
a

array([ 3, 24, 98, 96,  1, 46, 64, 40,  6, 18, 49, 80, 40, 70, 21])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)

In [5]:
b

array([[99, 64, 62, 91],
       [30, 35, 85, 22],
       [72, 90, 61, 32],
       [91, 48, 26, 99],
       [34, 54, 23, 79],
       [37, 24, 88, 34]])

In [6]:
np.sort(a)[::-1]

array([98, 96, 80, 70, 64, 49, 46, 40, 40, 24, 21, 18,  6,  3,  1])

In [7]:
np.sort(b,axis=0)

array([[30, 24, 23, 22],
       [34, 35, 26, 32],
       [37, 48, 61, 34],
       [72, 54, 62, 79],
       [91, 64, 85, 91],
       [99, 90, 88, 99]])

### 2. np.append:The numpy.append() appends values along the mentioned axis at the end of the array

In [8]:
np.append(a,200)

array([  3,  24,  98,  96,   1,  46,  64,  40,   6,  18,  49,  80,  40,
        70,  21, 200])

In [9]:
b

array([[99, 64, 62, 91],
       [30, 35, 85, 22],
       [72, 90, 61, 32],
       [91, 48, 26, 99],
       [34, 54, 23, 79],
       [37, 24, 88, 34]])

In [10]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[99.        , 64.        , 62.        , 91.        ,  0.96137981],
       [30.        , 35.        , 85.        , 22.        ,  0.45866205],
       [72.        , 90.        , 61.        , 32.        ,  0.20519085],
       [91.        , 48.        , 26.        , 99.        ,  0.98736427],
       [34.        , 54.        , 23.        , 79.        ,  0.6368904 ],
       [37.        , 24.        , 88.        , 34.        ,  0.61971829]])

### 3. np.concatenate:numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [11]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [12]:
print(c)

[[0 1 2]
 [3 4 5]]


In [13]:
print(d)

[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### 4. np.unique:With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [16]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### 5. np.expand_dims:With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

In [17]:
a.shape

(15,)

In [18]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [19]:
np.expand_dims(a,axis=1)

array([[ 3],
       [24],
       [98],
       [96],
       [ 1],
       [46],
       [64],
       [40],
       [ 6],
       [18],
       [49],
       [80],
       [40],
       [70],
       [21]])

### 6.np.where:The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [20]:
a

array([ 3, 24, 98, 96,  1, 46, 64, 40,  6, 18, 49, 80, 40, 70, 21])

#### find all indices with value greater than 50

In [21]:
np.where(a>50)

(array([ 2,  3,  6, 11, 13], dtype=int64),)

#### replace all values > 50 with 

In [22]:
np.where(a>50,0,a)

array([ 3, 24,  0,  0,  1, 46,  0, 40,  6, 18, 49,  0, 40,  0, 21])

In [23]:
np.where(a%2 == 0,0,a)

array([ 3,  0,  0,  0,  1,  0,  0,  0,  0,  0, 49,  0,  0,  0, 21])

### 7.np.argmax:The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [24]:
np.argmax(a)

2

In [25]:
b

array([[99, 64, 62, 91],
       [30, 35, 85, 22],
       [72, 90, 61, 32],
       [91, 48, 26, 99],
       [34, 54, 23, 79],
       [37, 24, 88, 34]])

In [26]:
np.argmax(b,axis=0)

array([0, 2, 5, 3], dtype=int64)

In [27]:
np.argmax(b,axis=1)

array([0, 2, 1, 3, 3, 2], dtype=int64)

In [28]:
# np.argmin
np.argmin(a)

4

### 8.np.cumsum:numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [29]:
np.cumsum(a)

array([  3,  27, 125, 221, 222, 268, 332, 372, 378, 396, 445, 525, 565,
       635, 656], dtype=int32)

In [30]:
np.cumsum(b,axis=1)

array([[ 99, 163, 225, 316],
       [ 30,  65, 150, 172],
       [ 72, 162, 223, 255],
       [ 91, 139, 165, 264],
       [ 34,  88, 111, 190],
       [ 37,  61, 149, 183]], dtype=int32)

In [31]:
np.cumsum(b)

array([  99,  163,  225,  316,  346,  381,  466,  488,  560,  650,  711,
        743,  834,  882,  908, 1007, 1041, 1095, 1118, 1197, 1234, 1258,
       1346, 1380], dtype=int32)

In [32]:
# np.cumprod
np.cumprod(a)

array([          3,          72,        7056,      677376,      677376,
          31159296,  1994194944, -1836580864,  1865416704,  -782237696,
         325058560,   234881024,   805306368,   536870912, -1610612736],
      dtype=int32)

### 9.np.percentile:numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis

In [33]:
np.percentile(a,50)

40.0

In [34]:
np.median(a)

40.0

### 10.np.histogram:Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [35]:
a

array([ 3, 24, 98, 96,  1, 46, 64, 40,  6, 18, 49, 80, 40, 70, 21])

In [36]:
np.histogram(a,bins=[0,50,100])

(array([10,  5], dtype=int64), array([  0,  50, 100]))

### 11.np.corrcoef:Return Pearson product-moment correlation coefficients.

In [37]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### 12.np.isin:With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [38]:
a

array([ 3, 24, 98, 96,  1, 46, 64, 40,  6, 18, 49, 80, 40, 70, 21])

In [39]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([40, 80, 40, 70])

### 13.np.flip:The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array

In [40]:
a

array([ 3, 24, 98, 96,  1, 46, 64, 40,  6, 18, 49, 80, 40, 70, 21])

In [41]:
np.flip(a)

array([21, 70, 40, 80, 49, 18,  6, 40, 64, 46,  1, 96, 98, 24,  3])

In [42]:
b

array([[99, 64, 62, 91],
       [30, 35, 85, 22],
       [72, 90, 61, 32],
       [91, 48, 26, 99],
       [34, 54, 23, 79],
       [37, 24, 88, 34]])

In [43]:
np.flip(b,axis=1)

array([[91, 62, 64, 99],
       [22, 85, 35, 30],
       [32, 61, 90, 72],
       [99, 26, 48, 91],
       [79, 23, 54, 34],
       [34, 88, 24, 37]])

### 14.np.put:The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [44]:
a

array([ 3, 24, 98, 96,  1, 46, 64, 40,  6, 18, 49, 80, 40, 70, 21])

In [45]:
np.put(a,[0,1],[110,530])

### 15.np.delete:The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis

In [46]:
a

array([110, 530,  98,  96,   1,  46,  64,  40,   6,  18,  49,  80,  40,
        70,  21])

In [47]:
np.delete(a,[0,2,4])

array([530,  96,  46,  64,  40,   6,  18,  49,  80,  40,  70,  21])

## 16. Set functions

In [48]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [49]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
np.intersect1d(m,n)

array([3, 4, 5])

In [51]:
np.setdiff1d(n,m)

array([6, 7])

In [52]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [53]:
m[np.in1d(m,1)]

array([1])

### 17.np.clip:numpy.clip() function is used to Clip (limit) the values in an array.

In [54]:
a

array([110, 530,  98,  96,   1,  46,  64,  40,   6,  18,  49,  80,  40,
        70,  21])

In [55]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 75, 25, 46, 64, 40, 25, 25, 49, 75, 40, 70, 25])