# What is numpy?
### NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic  linear algebra, basic statistical operations, random simulation and much more. At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

In [1]:
import numpy as np
import warnings 
warnings. filterwarnings('ignore')

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])# 2D
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])#  3D
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## dtype:Return the dtypes in the numpy array.

In [5]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

## np.arange:Return evenly spaced values within a given interval.

In [7]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

## with reshape:Reshaping we can add or remove dimensions or change number of elements in each dimension.

In [8]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

## np.ones:This is very similar to Numpy Zero. Here Numpy zeros function returns a numpy array of only ones with specified shape and data type.

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## np.zeros:Numpy zeros function returns a numpy array of only zeros with specified shape and data type.

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## np.random:generates random numbers from the standard uniform distribution

In [11]:
np.random.random((3,4))

array([[0.9231793 , 0.23323487, 0.39588595, 0.81642125],
       [0.41283949, 0.41873091, 0.53591806, 0.36722931],
       [0.70596792, 0.60612317, 0.68772013, 0.76875602]])

## np.linspace:Returns num evenly spaced samples, calculated over the interval

In [12]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

## np.identity:The identity array is a square array with ones on the main diagonal.

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [14]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## ndim:Number of array dimensions.

In [15]:
a3.ndim

3

## shape:Return the shape of an array.

In [16]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## size: is a function that is used to calculate the total elements or values for an axis in the given array

In [17]:
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

## itemsize:Returns the size (in bytes) of each element of a NumPy array.

In [18]:
a3.itemsize

4

## dtype:Return the dtypes in the numpy array.

In [19]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing Datatype

In [20]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Array Operations

In [21]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

# scalar operations

In [22]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [23]:
a1 - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [24]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [25]:
a1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [26]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [27]:
a1 // 2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]], dtype=int32)

In [28]:
a1 >2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# vector operations

In [29]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [30]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [31]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [32]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [33]:
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]], dtype=int32)

In [34]:
a1 % a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

# Array Functions

In [35]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

In [36]:
# max/min/sum/prod        0 -> col and 1 -> row
np.prod(a1,axis=0)

array([356004., 253820., 228068.])

In [37]:
# mean/median/std/var
np.var(a1,axis=1)

array([220.66666667, 152.        , 578.66666667])

In [38]:
# trigonomoetric functions
np.sin(a1)

array([[-0.02655115, -0.57338187, -0.85551998],
       [-0.7391807 , -0.98514626, -0.77946607],
       [-0.82181784, -0.42818267, -0.64353813]])

In [39]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [40]:
# log and exponents
np.exp(a1)

array([[4.60718663e+28, 3.63797095e+42, 1.25236317e+29],
       [8.43835667e+26, 1.37338298e+32, 9.01762841e+39],
       [6.07603023e+37, 1.58601345e+15, 1.17191424e+16]])

In [41]:
# round/floor/ceil
np.ceil(np.random.random((2,3))*100)

array([[80., 43., 16.],
       [91., 88., 10.]])

# Indexing and Slicing

In [42]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [43]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a2[1,0]

4

In [45]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [46]:
a3[1,0,1]

5

In [47]:
a3[1,1,0]

6

In [48]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a1[2:5:2]

array([2, 4])

In [50]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [52]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [53]:
a2[1,::3]

array([4, 7])

In [54]:
a2[0,:]

array([0, 1, 2, 3])

In [55]:
a2[:,2]

array([ 2,  6, 10])

In [56]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [57]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [58]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [59]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [60]:
a3[0,1,:]

array([3, 4, 5])

# Iterating

In [61]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [64]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [65]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [66]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

## Transpose: permutes or reserves the dimension of the given array and returns the modified array.

In [67]:
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## ravel: functions returns contiguous flattened array(1D array with all the input-array elements and with the same type as it).

In [68]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## horizontal stacking:Function is used to stack arrays in sequence horizontally (column wise). 

In [69]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [70]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

## Vertical stacking:function is used to stack the sequence of input arrays vertically to make a single array. 

In [71]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

## horizontal splitting:Split an array into multiple sub-arrays horizontally (column-wise).

In [72]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division